export const classes = {
  background: {
    dark: "bg-light-600 dark:bg-dark-700",
    base: "bg-light-500 dark:bg-dark-500",
    light: "bg-light-300 dark:bg-dark-300",
    hoverDark: "hover:bg-light-600 dark:hover:bg-dark-700",
    hoverBase: "hover:bg-light-500 dark:hover:bg-dark-500",
    hoverLight: "hover:bg-light-300 dark:hover:bg-dark-300",
    hoverDarkInverted: "dark:hover:bg-light-600 hover:bg-dark-700",
    hoverBaseInverted: "dark:hover:bg-light-500 hover:bg-dark-500",
    hoverLightInverted: "dark:hover:bg-light-300 hover:bg-dark-300",
    darkInverted: "dark:bg-light-600 bg-dark-700",
    baseInverted: "dark:bg-light-500 bg-dark-500",
    lightInverted: "dark:bg-light-300 bg-dark-300",
  },
  textBase: "text-dark-700 dark:text-light-300",
  textBaseInverted: "dark:text-dark-700 text-light-300",
  textHover: "hover:text-dark-300 dark:hover:text-light-500",
  textHoverInverted: "dark:hover:text-dark-300 hover:text-light-500",
  placeholder: "placeholder-dark-400 dark:placeholder-light-300",
  border: "border-light-200 dark:border-dark-300",
  borderHover: "hover:border-light-200 dark:hover:border-dark-300",
  borderDark: "border-dark-300 dark:border-light-400",
};
